# Generated by Django 5.0.1 on 2024-01-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
